---
name: hello

services:
  hello-1:
    image: bob2606/hello-http:0.8.30
    container_name: hello-1
    hostname: hello-1
    ports:
      - 8081:8080
    environment:
      MSG: Hello-1
    deploy:
      resources:
        limits:
          cpus: "0.1"
    networks:
      hellonet:
      traefiknet:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_traefiknet
      - traefik.http.routers.hello-1.rule=Host(`www.hello-1.stage`)

  hello-2:
    image: bob2606/hello-http:0.8.30
    container_name: hello-2
    hostname: hello-2
    ports:
      - 8082:8080
    environment:
      MSG: Hello-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
    networks:
      hellonet:
      traefiknet:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_traefiknet
      - traefik.http.routers.hello-2.rule=PathPrefix(`/hello-2`)
      - traefik.http.middlewares.hello-2-strip.stripprefix.prefixes=/hello-2
      - traefik.http.routers.hello-2.middlewares=hello-2-strip

  hello-3:
    image: bob2606/hello-http:0.8.30
    container_name: hello-3
    hostname: hello-3
    ports:
      - 8083:8080
    environment:
      MSG: Hello-3
    deploy:
      resources:
        limits:
          cpus: "0.1"
    networks:
      hellonet:
      traefiknet:
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_traefiknet
      - traefik.http.routers.hello-3.rule=(Host(`www.hello-3.stage`)&&(PathPrefix(`/hello-3`)))
      - traefik.http.middlewares.hello-3-strip.stripprefix.prefixes=/hello-3
      - traefik.http.routers.hello-3.middlewares=hello-3-strip

networks:
  hellonet:
  traefiknet:
    name: proxy_traefiknet
    external: true
