---
name: lemp
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 5

services:
  www:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: www
    hostname: www
    ports:
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_SUBNET_PREFIX}.${NGINX_IPV4_ADDRESS}
    depends_on:
      - php
    restart: unless-stopped
    <<: *default-logging

  php:
    image: php:8.2-fpm
    container_name: php
    hostname: phpsrv
    volumes:
      - ./html:/var/www/html
      - ./html:/mnt
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_SUBNET_PREFIX}.${PHP_IPV4_ADDRESS}
    restart: unless-stopped
    <<: *default-logging

  db:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: db
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_SUBNET_PREFIX}.${MARIADB_IPV4_ADDRESS}
    restart: unless-stopped
    <<: *default-logging

volumes:
  db:

networks:
  lempnet:
    ipam:
      config:
        - subnet: ${LEMPNET_SUBNET_PREFIX}.0.0/16
          gateway: ${LEMPNET_SUBNET_PREFIX}.${LEMPNET_GATEWAY}
    driver_opts:
      com.docker.network.bridge.name: lempnet0
