---
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 5

services:
  www:
    image: nginx:1.28
    container_name: www
    hostname: www
    ports:
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    networks:
      lempnet:
        ipv4_address: 172.25.0.80
    depends_on:
      - php
    restart: unless-stopped
    <<: *default-logging

  php:
    image: php:8.2-fpm
    container_name: php
    hostname: phpsrv
    volumes:
      - ./html:/var/www/html
      - ./html:/mnt
    networks:
      lempnet:
        ipv4_address: 172.25.0.90
    restart: unless-stopped
    <<: *default-logging

  db:
    image: mariadb:10.8
    container_name: db
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    <<: *default-logging

volumes:
  db:

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
